### ISSUE TITLE
bitbucket.org auth fail

### ISSUE THREAD

**Issue by hanskoff** [ajoberstar/grgit#115]
Hi,
I'm happy user of your plugin but when I try to pull from bitbucket.org repository I see

```
Caused by: org.eclipse.jgit.api.errors.TransportException: git@bitbucket.org:hanskoff/sample.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:134)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:267)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:80)
	at java_util_concurrent_Callable$call$2.call(Unknown Source)
	at org.ajoberstar.grgit.operation.PullOp.call(PullOp.groovy:96)
	... 83 more
Caused by: org.eclipse.jgit.errors.TransportException: git@bitbucket.org:hanskoff/sample.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:264)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	... 87 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 94 more
```

Do you know how should be ssh/config be configured on my side?
I use osx, and ssh key as way to authorise to bitbucket and from command line it works well...

**Comment by hanskoff** [comment]
excuse me, I've just read the manual
http://ajoberstar.org/grgit/docs/groovydoc/index.html?org/ajoberstar/grgit/Grgit.html
and everything is clear

**Comment by Mithilesh8144** [comment]
Hey the link you mentioned doesnt exist, could you specify how you solved this issue?
