### ISSUE TITLE
Merging resolved changes

### ISSUE THREAD

**Issue by Blacktiger** [ajoberstar/grgit#116]
This is a followup to #110 and #112. I'm now able to identify the merge conflicts and fix them. Once I do, I try to add and commit the changes to close out the merge, but jgit doesn't let me.

```
try {
	project.git.repository.merge(head: 'master', mode: Mode.CREATE_COMMIT)
} catch (GrgitException e) {
	mergeFailureStrategy.handleMergeFailure(e)
	project.git.repository.add(patterns: ['build.gradle'])
	project.git.repository.commit(message: '[Build] Merge branch "master" and update project version to ${project.semver.newVersion}')
}
```

```
Caused by: org.eclipse.jgit.api.errors.WrongRepositoryStateException: Cannot commit on a repo with state: MERGING
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:175)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:102)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.CommitOp.call(CommitOp.groovy:121)
	... 76 more
```

I'm investigating jgit to try to figure out what I'll need to finalize the merge, but I'm not very familiar with jgit. In any event, I'm guessing another change to grgit will be needed to let me programmatically merge these changes.

**Comment by Blacktiger** [comment]
Oh, haha. I added the wrong file since I merged gradle.properties not build.gradle. I'm closing this issue since I didn't actually need changes.
