### ISSUE TITLE
Auth failed with ssh key and passphrase

### ISSUE THREAD

**Issue by cHullaert** [ajoberstar/grgit#144]
I put my rsa key and my passphrases like this on windows and each time i get AUTHFAILED

System.properties.'org.ajoberstar.grgit.auth.ssh.passphrase' = "mypassphrase"
repository=Grgit.clone(dir: localPath, uri: remotePath)

**Comment by cHullaert** [comment]
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:cHullaert/superobject.git: USERAUTH fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:160) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:137) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:264) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1201) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:203) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:136) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:85) ~[org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]

**Comment by ajoberstar** [comment]
While this feature has been merged into master, I haven't yet made a new release that includes it. Once 1.9.0 is out, you should be able to give it a try again.

**Comment by ajoberstar** [comment]
I'll have that release out tonight.

**Comment by HakChealKim** [comment]
is it anyone find the solution?
online waiting........
