### ISSUE TITLE
How do you use default SSH for auth?

### ISSUE THREAD

**Issue by pluttrell** [ajoberstar/grgit#148]
I'm attempting to use `grgit` through the `nebula-release-plugin`. I have not provided it any auth configuration as I would like it to use the default ssh keys installed on my machine which already works, as shown here:

```
$ git pull
Already up-to-date.
```

If I run a build through `nebula-release-plugin`, it fails and here's the cause:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepare'.
        [omitted for brevity]
Caused by: org.ajoberstar.grgit.exception.GrgitException: Problem fetching from remote.
        at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:100)
        at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
        at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:188)
        at org.ajoberstar.gradle.git.release.base.BaseReleasePlugin$_addPrepareTask_closure2_closure5.doCall(BaseReleasePlugin.groovy:58)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:pluttrell/nebula-tests.git: Auth fail
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:76)
        at java_util_concurrent_Callable$call$0.call(Unknown Source)
        at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:97)
        ... 80 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:pluttrell/nebula-tests.git: Auth fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        ... 83 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:512)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
        ... 90 more
```

Is there a way to get `grgit` to use the ssh keys already installed and configured?

**Comment by kevbo23** [comment]
Is there any chance that Git root is in a different path than Gradle root?  Try this:
./gradlew -Pgit.root=<git root path> final

**Comment by ajoberstar** [comment]
@kevbo23 Is `git.root` something specific to nebula? I'm pretty sure it's not part of any of my plugins.

@pluttrell The existing docs are in [AuthConfig](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/auth/AuthConfig.html), though they may not cover in enough detail. If you have ssh-agent or Pageant running it should be working with no extra config. If not, it may try to use the default SSH key location, but I'm not positive off the top of my head. If you want to force the specific key, see the system properties mentioned in AuthConfig for setting the key and passphrase.

You can also try running with `--info` to see additional information from grgit about what it's using.

**Comment by kevbo23** [comment]
@ajoberstar git.root is specific to nebula.  This is how nebula opens grgit:
```
def gitRoot = project.hasProperty('git.root') ? project.property('git.root') : roject.rootProject.projectDir
git = Grgit.open(dir: gitRoot)
```
And that is why I was wondering about git.root.

**Comment by ajoberstar** [comment]
Makes sense

**Comment by ajoberstar** [comment]
Feel free to reopen if you have further info or questions.
