### ISSUE TITLE
Resolving commit to Tag throws NPE

### ISSUE THREAD

**Issue by eaaltonen** [ajoberstar/grgit#154]
I have code that checks whether the current commit is a tag.
```groovy
plugins { 
    id 'org.ajoberstar.grgit' version '1.6.0'
}
import org.ajoberstar.grgit.Grgit
def grgit  = Grgit.open()
def head = grgit.head()
def commit_id = grgit.head().id
def tag = grgit.resolve.toTag(commit_id)
```

Running this is a Git repository without any tags, throws the following exception:
```
Caused by: java.lang.NullPointerException: Cannot get property 'name' on null object
        at org.ajoberstar.grgit.util.JGitUtil.resolveTag(JGitUtil.groovy:176)
        at org.ajoberstar.grgit.util.JGitUtil$resolveTag$3.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveTag(JGitUtil.groovy:165)
        at org.ajoberstar.grgit.util.JGitUtil$resolveTag$2.call(Unknown Source)
        at org.ajoberstar.grgit.service.ResolveService.toTag(ResolveService.groovy:133)
        at org.ajoberstar.grgit.service.ResolveService$toTag$0.call(Unknown Source)
```

, which is IMO not very graceful.

**Comment by ajoberstar** [comment]
The Javadoc should be more clear on this, error message could be too... The resolve toTag method expects a String with a ref name, not a commit id. For your use case, you need to start with a list of tags, then filter that list to find tags pointing to your commit.

**Comment by eaaltonen** [comment]
Actually what I'm looking for is calling `git describe` and then checking, if that is tag or not.

JGit seems to have the command available
http://download.eclipse.org/jgit/site/4.6.1.201703071140-r/apidocs/org/eclipse/jgit/api/DescribeCommand.html

I suppose the list & filter would work too.

**Comment by ajoberstar** [comment]
Git describe is supported already, here's a link to [the doc](http://ajoberstar.org/grgit/docs/groovydoc/org/ajoberstar/grgit/operation/DescribeOp.html).
