### ISSUE TITLE
com.jcraft.jsch.agentproxy.AgentProxyException: netcat does not support -U option

### ISSUE THREAD

**Issue by eku** [ajoberstar/grgit#213]
System: Fedora 27
Groovy: 2.4.8 JVM: 1.8.0_151 Vendor: Oracle Corporation OS: Linux
Neither GNU's NetCat nor Nmap's Netcat replacement have option ```-U```.

```
10:18:24.405 [INFO] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] NetCat USocketFactory could not be configured: netcat does not support -U option.
10:18:24.405 [DEBUG] [org.ajoberstar.grgit.auth.JschAgentProxySessionFactory] NetCat USocketFactory failure details
com.jcraft.jsch.agentproxy.AgentProxyException: netcat does not support -U option.
        at com.jcraft.jsch.agentproxy.usocket.NCUSocketFactory.<init>(NCUSocketFactory.java:70)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
        at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory$_closure4.doCall(JschAgentProxySessionFactory.groovy:171)
        at org.ajoberstar.grgit.auth.JschAgentProxySessionFactory$_closure4.doCall(JschAgentProxySessionFactory.groovy)
```

**Comment by ajoberstar** [comment]
That ends up happening in the implementation of JSCH's agent proxy code, so I don't think there's anything I can do from my side. grgit should be catching the exception, so that it can try other options, if they're available.

Are you see it go through all of the auth options and then bomb with some kind of authentication issue?

**Comment by eku** [comment]
@ajoberstar no, it fails on the first  try with the mentioned exception.

**Comment by ajoberstar** [comment]
What version of grgit are you using? [As of 2.0.0](https://github.com/ajoberstar/grgit/commit/5f5a9601f23ad6126cf68fafa073782d993d4850) this should be caught and logged, but shouldn't cause a direct failure. It may still fail due to no other authentication working either, but this exception shouldn't bubble up anymore. If so, that's a bug.

**Comment by ajoberstar** [comment]
Feel free to reopen if you want to continue looking at this.
