### ISSUE TITLE
org.eclipse.jgit.api.errors.TransprotException

### ISSUE THREAD

**Issue by sardar12** [ajoberstar/grgit#220]
Hi,
    I am facing the following error while trying to do team pull in my project in eclipse. 

org.eclipse.jgit.api.errors.TransprotException

Please advise. Cheers

**Comment by sardar12** [comment]
org.eclipse.jgit.api.errors.TransportException: https://github.com/
git-upload-pack not permitted
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:135)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:280)
	at org.eclipse.egit.core.op.PullOperation$1.run(PullOperation.java:193)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.PullOperation.execute(PullOperation.java:225)
	at org.eclipse.egit.ui.internal.pull.PullOperationUI.execute(PullOperationUI.java:176)
	at org.eclipse.egit.ui.internal.pull.PullOperationUI.access$0(PullOperationUI.java:168)
	at org.eclipse.egit.ui.internal.pull.PullOperationUI$1.runInWorkspace(PullOperationUI.java:141)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/TasWater/anywhere_development.git: git-upload-pack not permitted
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:501)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:290)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1201)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	... 9 more

**Comment by ajoberstar** [comment]
This looks like a permissions issue to me. What are using for credentials? and do those credentials have write access to the repository?

**Comment by sardar12** [comment]
Hi,
    Thanks for your email. I believe you are after this information

[cid:image001.png@01D3BF58.F42CA470]


I am not sure what happened at once that has caused it stop working. Few days back it was working fine not now has stopped working. Yes this credentials have write access to repository. Cheers

**Comment by ajoberstar** [comment]
Your screenshot seems to have been dropped in transmission.

**Comment by sardar12** [comment]
My screen shot is as follows
![1](https://user-images.githubusercontent.com/23709419/37627680-73fe38b8-2bcd-11e8-9479-d49799f01813.GIF)
![2](https://user-images.githubusercontent.com/23709419/37627712-98793cd8-2bcd-11e8-92ce-6cdc217727a0.GIF)

**Comment by ajoberstar** [comment]
OK, so that covers the config of your repo itself. Are you using anything like what is specified in [grgit's authentication docs](http://ajoberstar.org/grgit/grgit-authentication.html)?

I would expect that you could get by with clone/fetch/pull without providing the username/password, but the pushes shouldn't have worked before if you didn't have that configured.

**Comment by ajoberstar** [comment]
Scratch all of that, I completely misread your original email. This looks like an issue with JGit and/or the EGit plugin for Eclipse. I don't think this is tied to grgit at all. I'm not exactly sure where the best channel for support on those would be.

**Comment by Berky115** [comment]
Hey, same issue on my end. Was the fix upgrading jGit or credentials changes?
