### ISSUE TITLE
grgit.branch.current() fails

### ISSUE THREAD

**Issue by WvdWvD** [ajoberstar/grgit#229]
Since this morning (2018-05-31T06:11:28.179Z) my build fails on "grgit.branch.current()" with the message:

```
No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (java.lang.String) values: [HEAD]
  Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()
```

The call to FileRepository.getRef() is on line 44 of [org.ajoberstar.grgit.service.BranchService ](https://github.com/ajoberstar/grgit/blob/e1e48612b508a406dcc91ab102c5fe2c82d54e7b/src/main/groovy/org/ajoberstar/grgit/service/BranchService.groovy#L44)(current master).

Interestingly enough in this particular build 'org.eclipse.jgit' and 'org.eclipse.jgit.ui' have been update to update version '5.0.0.201805151920-m7'.

I have this issue with grgit version 2.1.1 aswell as 2.2.0.

**Comment by urisun** [comment]
Even we are facing the same issue. More details:
Caused by: groovy.lang.MissingMethodException: No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (java.lang.String) values: [HEAD]
Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()
        at org.ajoberstar.grgit.service.BranchService.current(BranchService.groovy:44)
        at org.ajoberstar.grgit.service.BranchService$current.call(Unknown Source)
        at build_3p76j616ztur3ib4y2050x2m$_run_closure8.doCall(/Users/vwwud01/work/GIT/jarvis_apis/build.gradle:75)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:215)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_3p76j616ztur3ib4y2050x2m.run(/Users/vwwud01/work/GIT/jarvis_apis/build.gradle:72)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 50 more

**Comment by ajoberstar** [comment]
I was under the mistaken assumption that my POMs were being published with static versions, but it seems the `com.gradle.plugin-publish` plugin doesn't respect the POM modifications to do that.

I'll push out a quick fix to cap the version so it doesn't include v5. But later today I'll figure out how to get static versions published again in the POM.

**Comment by ajoberstar** [comment]
I'm gong to have to head off to work, but if [this build succeeds](https://circleci.com/workflow-run/7a9f133f-a0fd-4e94-8067-e5a9cbaecd79) there will be a 2.2.1-rc.2 which should statically include JGit 4.11. If that doesn't work or if you need something sooner, you'll need to use the buildscript block to force a specific JGit version to be pulled in.

I still plan to get a final fix out tonight.

**Comment by aemyers** [comment]
Thank you for the quick fix!

I was building a project last night that suddenly wouldn't build for a release I needed today... I love the simplicity of this plugin. Keep up the great work! :)

**Comment by ajoberstar** [comment]
I'll leave this open until I publish 2.2.1 final (see not in #234 for why that hasn't happened yet). Plan is to wrap this up tonight.

**Comment by ajoberstar** [comment]
2.2.1 is out now
