### ISSUE TITLE
Compatibility with Groovy 2.5

### ISSUE THREAD

**Issue by dawidsawa** [ajoberstar/grgit#237]
Perhaps due to some `@Immutable` AST transformation changes in [Groovy 2.5](http://groovy-lang.org/releasenotes/groovy-2.5.html), some methods are failing now.

`Grgit.open().head()` fails with the following:
```
Caught: java.lang.RuntimeException: Unsupported type (org.ajoberstar.grgit.Person) found for field 'author' while constructing immutable class org.ajoberstar.grgit.Commit.
Immutable classes only support properties with effectively immutable types including:
- Strings, primitive types, wrapper types, Class, BigInteger and BigDecimal, enums
- classes annotated with @KnownImmutable and known immutables (java.awt.Color, java.net.URI)
- Cloneable classes, collections, maps and arrays, and other classes with special handling
  (java.util.Date and various java.time.* classes and interfaces)
Other restrictions apply, please see the groovydoc for ImmutableOptions for further details
java.lang.RuntimeException: Unsupported type (org.ajoberstar.grgit.Person) found for field 'author' while constructing immutable class org.ajoberstar.grgit.Commit.
Immutable classes only support properties with effectively immutable types including:
- Strings, primitive types, wrapper types, Class, BigInteger and BigDecimal, enums
- classes annotated with @KnownImmutable and known immutables (java.awt.Color, java.net.URI)
- Cloneable classes, collections, maps and arrays, and other classes with special handling
  (java.util.Date and various java.time.* classes and interfaces)
Other restrictions apply, please see the groovydoc for ImmutableOptions for further details
        at org.ajoberstar.grgit.Commit.<init>(Commit.groovy)
        at org.ajoberstar.grgit.util.JGitUtil.convertCommit(JGitUtil.groovy:134)
        at org.ajoberstar.grgit.util.JGitUtil$convertCommit$2.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveCommit(JGitUtil.groovy:109)
        at org.ajoberstar.grgit.util.JGitUtil$resolveCommit$1.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveCommit(JGitUtil.groovy:98)
        at org.ajoberstar.grgit.util.JGitUtil$resolveCommit$0.call(Unknown Source)
        at org.ajoberstar.grgit.service.ResolveService.toCommit(ResolveService.groovy:93)
        at org.ajoberstar.grgit.service.ResolveService$toCommit.call(Unknown Source)
        at org.ajoberstar.grgit.Grgit.head(Grgit.groovy:153)
        at org.ajoberstar.grgit.Grgit$head$0.call(Unknown Source)
```

`Grgit.open().branch.getCurrent()` fails with the following:
```
Caught: java.lang.RuntimeException: Unsupported type (org.ajoberstar.grgit.Branch) found for field 'trackingBranch' while constructing immutable class org.ajoberstar.grgit.Branch.
Immutable classes only support properties with effectively immutable types including:
- Strings, primitive types, wrapper types, Class, BigInteger and BigDecimal, enums
- classes annotated with @KnownImmutable and known immutables (java.awt.Color, java.net.URI)
- Cloneable classes, collections, maps and arrays, and other classes with special handling
  (java.util.Date and various java.time.* classes and interfaces)
Other restrictions apply, please see the groovydoc for ImmutableOptions for further details
java.lang.RuntimeException: Unsupported type (org.ajoberstar.grgit.Branch) found for field 'trackingBranch' while constructing immutable class org.ajoberstar.grgit.Branch.
Immutable classes only support properties with effectively immutable types including:
- Strings, primitive types, wrapper types, Class, BigInteger and BigDecimal, enums
- classes annotated with @KnownImmutable and known immutables (java.awt.Color, java.net.URI)
- Cloneable classes, collections, maps and arrays, and other classes with special handling
  (java.util.Date and various java.time.* classes and interfaces)
Other restrictions apply, please see the groovydoc for ImmutableOptions for further details
        at org.ajoberstar.grgit.Branch.<init>(Branch.groovy)
        at org.ajoberstar.grgit.util.JGitUtil.resolveBranch(JGitUtil.groovy:209)
        at org.ajoberstar.grgit.util.JGitUtil$resolveBranch.call(Unknown Source)
        at org.ajoberstar.grgit.service.BranchService.current(BranchService.groovy:60)
        at org.ajoberstar.grgit.service.BranchService.getCurrent(BranchService.groovy:70)
        at org.ajoberstar.grgit.service.BranchService$getCurrent.call(Unknown Source)
```

**Comment by ajoberstar** [comment]
Thanks for the report, I'll get this fixed in the next release.
