### ISSUE TITLE
No .git directory found! OpenJDK-11, using id "org.ajoberstar.grgit" version "3.0.0"

### ISSUE THREAD

**Issue by SchlauFuchs** [ajoberstar/grgit#269]
Stacktrace:

```
Caused by: java.lang.IllegalStateException: No .git directory found!
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:59)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.ajoberstar.grgit.internal.OpSyntax.noArgOperation(OpSyntax.groovy:10)
        at org.ajoberstar.grgit.internal.OpSyntax$noArgOperation$0.callStatic(Unknown Source)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
        at org.ajoberstar.grgit.Grgit$open$0.call(Unknown Source)
        at build_2lgm5hatn3498g3wpoa7wqxon$_run_closure1.doCall(C:\Users\kaiha\Documents\eclipse-workspace\dynatraceripper\build.gradle:31)
```

**Comment by ajoberstar** [comment]
Hi @SchlauFuchs. Do you have any more context of what code fails in your build file? Does this same code work on Java 8 or an earlier version of grgit?

**Comment by SchlauFuchs** [comment]
The project was on hold for a few months. It worked with Java 10. It was
not exposed to earlier versions of Java. I had it originally configured to
use
dependencies {
        classpath 'org.ajoberstar:grgit:3.3'

but then tried with the latest version after Java upgrade.

**Comment by ajoberstar** [comment]
I haven't been able to run my test suite on 11, but I think that's just some Groovy compiler incompatibility. Grgit seems to operate fine when applied to my other projects running on 11. 

It looks like you're making an explicit `Grgit.open` call in your build file (line 31). Can you post that code and double check that it's pointing to a directory that contains a Git repo?

**Comment by SchlauFuchs** [comment]
It worked before so this is the code that worked before:

ext {
    def repo = Grgit.open()
    def head = repo.head()
    def tags = repo.tag.list().findAll { it.commit == head }
    revision = tags.size>0?tags[0].fullName:head.id
}

The build.gradle is in the root of the git project, and a .git folder is
definitely there.

Cheers,
Kai

**Comment by ajoberstar** [comment]
Hard to say how f this is the issue, but Gradle doesn't guarantee what the build process's working directly will be. I'd recommend something like:

```
Grgit grgit = Grgit.open(currentDir: project.rootDir)``

**Comment by SchlauFuchs** [comment]
This workaround helped. Thank you. But it would still be good to find out
what the breaking change was

**Comment by ajoberstar** [comment]
In one of your previous replies, you said your dependency on grgit looked like:
> ```
> classpath 'org.ajoberstar:grgit:3.3'
> ```

Since that version doesn't exist, what was the specific version you were previously on that worked in Java 10? Maybe one of:

- `org.ajoberstar.grgit:grgit-core:3.0.0-rc.3`
- `org.ajoberstar.grgit:grgit-core:3.0.0-beta.1`
- `org.ajoberstar:grgit:2.3.0`

Knowing the specific version would make it easier to look into any breaking change.

**Comment by SchlauFuchs** [comment]
Hi,

it exists: https://mvnrepository.com/artifact/org.ajoberstar/grgit/3.3

I am currently away from my sources, I look the previous string up later
today.

**Comment by ajoberstar** [comment]
Hmm, that's odd... Definitely not an intentional release. Based on the date (Jan 5 2017) and the deps in the POM file, 3.3 looks more likely to be based on the [1.8.0](https://github.com/ajoberstar/grgit/releases/tag/1.8.0) code, instead of being anything close to the 3.0.0 that was just released. Too many changes between those to speak to anything specific that would break your previous code.

**Comment by vonkad** [comment]
In my Kotlin gradle build, the syntax is
`val git = Grgit.open(mapOf("currentDir" to project.rootDir))`

**Comment by jmini** [comment]
As far as I can tell the issue is still present with the newest version `4.0.1`.

Here is a simple `gradle.build` file:

```
plugins {
    id 'org.ajoberstar.grgit' version '4.0.1' apply false
}

task printCommitId {
    doLast {
        println "Current commit id: " + org.ajoberstar.grgit.Grgit.open().head().id
    }
}
```

Tested with Gradle `5.6.4`, with JVM `1.8.0_202` it works:

```
> Task :printCommitId
Current commit id: 0673c47f04e6efeae69d461455279fe59e643d23
```

Tested with Gradle `5.6.4`, with JVM `11.0.5` it does not work:

```
> Task :printCommitId FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/__/build.gradle' line: 7

* What went wrong:
Execution failed for task ':printCommitId'.
> No .git directory found!
```

with `--stacktrace` I think the interesting part is here:
```
Caused by: java.lang.IllegalStateException: No .git directory found!
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:59)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call$0.call(Unknown Source)
        at org.ajoberstar.grgit.internal.OpSyntax.noArgOperation(OpSyntax.groovy:10)
        at org.ajoberstar.grgit.internal.OpSyntax$noArgOperation.callStatic(Unknown Source)
        at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
        at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)
```

**Comment by jmini** [comment]
@ajoberstar did you see my last comment? I suggest to reopen this issue.

**Comment by fabmars** [comment]
Our company encountered this error following IntelliJ 2021.1 update. They are probably running the IDE with a JRE11 now which chances the Gradle behavior as explained here: https://github.com/gradle/gradle/issues/9764

Deep down, the issue stems from here: Le problème est là https://github.com/eclipse/jgit/blob/983c25064edeada19bd46aa604a9b90e23778a90/org.eclipse.jgit/src/org/eclipse/jgit/lib/BaseRepositoryBuilder.java#L536

The solution is indeed to follow @ajoberstar's advice here: https://github.com/ajoberstar/grgit/issues/269#issuecomment-441308503
