### ISSUE TITLE
Don't crash when commit isn't found in log op

### ISSUE THREAD

**Issue by SUPERCILEX** [ajoberstar/grgit#272]
Using `log { range(non-existent, head) }` will crash with an NPE as shown below. It should just return an empty list instead.

```
Caused by: java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:138)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:887)
	at org.eclipse.jgit.revwalk.RevWalk$parseAny.call(Unknown Source)
	at org.eclipse.jgit.revwalk.RevWalk$parseAny.call(Unknown Source)
	at org.ajoberstar.grgit.util.JGitUtil.resolveRevObject(JGitUtil.groovy:57)
	at org.ajoberstar.grgit.util.JGitUtil$resolveRevObject.call(Unknown Source)
	at org.ajoberstar.grgit.operation.LogOp$_call_closure1.doCall(LogOp.groovy:50)
	at org.ajoberstar.grgit.operation.LogOp.call(LogOp.groovy:56)
	at org.ajoberstar.grgit.operation.LogOp.call(LogOp.groovy)
```

**Comment by ajoberstar** [comment]
CLI git seems to fail in this scenario too:

```
$ git log noexist...master
fatal: ambiguous argument 'noexist...master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Maybe just needs a better error message?
