### ISSUE TITLE
NullPointerException when resolving a non-existent commit

### ISSUE THREAD

**Issue by Vampire** [ajoberstar/grgit#298]
I tried to get a non-existent commit.
In my case it was `HEAD` on an orphaned branch where naturally no head reference is present, the same should happen on a newly initialized repository though.
In that situation I called `Grgit.head()` which resulted in the following exception:

```
Caused by: java.lang.NullPointerException
        at org.eclipse.jgit.lib.Repository.resolve(Repository.java:531)
        at org.eclipse.jgit.lib.Repository.resolve(Repository.java:492)
        at org.eclipse.jgit.lib.Repository$resolve.call(Unknown Source)
        at org.eclipse.jgit.lib.Repository$resolve.call(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveObject(JGitUtil.groovy:43)
        at org.ajoberstar.grgit.util.JGitUtil.resolveCommit(JGitUtil.groovy:86)
        at org.ajoberstar.grgit.util.JGitUtil$resolveCommit$0.callStatic(Unknown Source)
        at org.ajoberstar.grgit.util.JGitUtil.resolveCommit(JGitUtil.groovy:87)
        at org.ajoberstar.grgit.util.JGitUtil$resolveCommit$0.call(Unknown Source)
        at org.ajoberstar.grgit.service.ResolveService.toCommit(ResolveService.groovy:78)
        at org.ajoberstar.grgit.service.ResolveService$toCommit.call(Unknown Source)
        at org.ajoberstar.grgit.Grgit.head(Grgit.groovy:138)
```

The reason is in `org.ajoberstar.grgit.util.JGitUtil#resolveCommit(org.ajoberstar.grgit.Repository, java.lang.String)`:
```java
  static Commit resolveCommit(Repository repo, String revstr) {
    ObjectId id = resolveObject(repo, revstr)
    return resolveCommit(repo, id)
  }
```

`resolveObject` for a string that cannot be resolved to an object id returns `null` according to situation and also its JavaDoc.
`resolveCommit(repo, id)` then recursively calls itself (not the object id overload like it would be in Java) which then results in the call `resolveObject(repo, null)` which then ultimately throws the `NullPointerException`.

I guess the correct fix would be
```java
  static Commit resolveCommit(Repository repo, String revstr) {
    ObjectId id = resolveObject(repo, revstr)
    return id ? resolveCommit(repo, id) : null
  }
```

**Comment by ajoberstar** [comment]
Thanks for reporting, will fix in next release.
