### ISSUE TITLE
java.lang.AbstractMethodError: needs new version to be compiled with new JGit

### ISSUE THREAD

**Issue by john-tipper** [ajoberstar/grgit#309]
I am getting a `java.lang.AbstractMethodError` when testing a project (https://github.com/allegro/axion-release-plugin) that uses this project and the latest version of JGit (released today, 18 Dec 2019, `5.6.0.201912101111-r`).  I think this means that an interface has changed in JGit and this project needs to be recompiled.

The dependencies in this project are set to pull in the latest version of JGit.  Please would you mind releasing a new recompiled version so I can make progress?

```
Missing implementation of resolved method abstract openJGitConfig(Lorg/eclipse/jgit/lib/Config;Lorg/eclipse/jgit/util/FS;)Lorg/eclipse/jgit/storage/file/FileBasedConfig; of abstract class org.eclipse.jgit.util.SystemReader.
java.lang.AbstractMethodError: Missing implementation of resolved method abstract openJGitConfig(Lorg/eclipse/jgit/lib/Config;Lorg/eclipse/jgit/util/FS;)Lorg/eclipse/jgit/storage/file/FileBasedConfig; of abstract class org.eclipse.jgit.util.SystemReader.
	at org.eclipse.jgit.util.SystemReader.getJGitConfig(SystemReader.java:381)
	at org.eclipse.jgit.util.SystemReader.getSystemConfig(SystemReader.java:406)
	at org.eclipse.jgit.util.SystemReader.getUserConfig(SystemReader.java:354)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:191)
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:616)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:123)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:278)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:199)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:1)
	at org.ajoberstar.grgit.operation.CloneOp.call(CloneOp.groovy:82)
	at org.ajoberstar.grgit.internal.OpSyntax.mapOperation(OpSyntax.groovy:20)

```

Where the offending method was called like this:

```
Grgit.clone(dir: repositoryDir, uri: "file://${cloneFrom.canonicalPath}")
```

**Comment by ajoberstar** [comment]
4.0.1 being release now to fix this. Thanks for reporting!
