### ISSUE TITLE
No .git directory found!

### ISSUE THREAD

**Issue by rahulr4** [ajoberstar/grgit#337]
Hi,
We have created a plugin and it was working fine up until android studio version 4.0.1 but since we have upgraded to 4.2.0 and gradle to 6.5-all (4.1.0), it is throwing an error:

`Caused by: java.lang.IllegalStateException: No .git directory found!
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor202.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:59)
	at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.internal.OpSyntax.noArgOperation(OpSyntax.groovy:10)
	at org.ajoberstar.grgit.internal.OpSyntax$noArgOperation.callStatic(Unknown Source)
	at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
	at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)
	at com.dminc.gradle.ReleaseConfigExtension.<init>(ReleaseConfigExtension.groovy:65)`

**Comment by rahulr4** [comment]
Issue has been resolved by giving the relative root path as Grgit.open() is not working on Android Studio 4.2.0
 //https://ajoberstar.org/grgit/grgit-open.html
+        def file = project.file('../')
+        project.logger.quiet("[ARP]:file path: '${file.getAbsoluteFile()}'.")
+        this.repository = Grgit.open(file)
