### ISSUE TITLE
Problem with self signed SSL cerificates - Secure connection could not be established because of SSL problems

### ISSUE THREAD

**Issue by aborunski** [ajoberstar/grgit#363]
Hello,

I'm trying execute push in my groovy class using `Grgit` but when calling `grgit.push()` I' receiving following error:

```
Caused by: org.gradle.internal.UncheckedException: org.eclipse.jgit.api.errors.TransportException: https://my-repo/project.git: Secure connection to https://my-repo/project.git.git could not be established because of SSL problems
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:431)
```

My repo is using custom self signed SSL certificates which I've added to `C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt`. I'm able to call `git push` from command line but `grgit` gives above error. Is there a way to pass `ca-bundle.crt` to `grgit` configuration?

**Comment by ajoberstar** [comment]
My gut is that JGit would be using the JDK's SSL implementation, which means you need to update the `cacerts` keystore that it uses by default to include the additional certs you want or override the path to the trust store. You'll probably need a p12 or jks.

https://stackoverflow.com/a/19280273
