### ISSUE TITLE
org.eclipse.jgit.api.errors.TransportException: https://github.com/xx/yy.git: not authorized when running release command

### ISSUE THREAD

**Issue by dunedodo** [ajoberstar/grgit#396]
I'm getting the following exception when running ./gradlew release command on my application. Please help take a look and suggest.

```
Caused by: org.eclipse.jgit.api.errors.TransportException: https://github.com/xx/yy.git: not authorized
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:147)
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:1)
        at java_util_concurrent_Callable$call$6.call(Unknown Source)
        at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:82)
        at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy)
        at java_util_concurrent_Callable$call$5.call(Unknown Source)
        at java_util_concurrent_Callable$call$5.call(Unknown Source)
        at org.ajoberstar.grgit.internal.OpSyntax.samOperation(OpSyntax.groovy:26)
        at org.ajoberstar.grgit.internal.OpSyntax$samOperation.callStatic(Unknown Source)
        at org.ajoberstar.grgit.Grgit.push(Grgit.groovy)
        at org.ajoberstar.gradle.git.publish.tasks.GitPublishPush.push(GitPublishPush.java:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ... 119 more
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/xx/yy.git: not authorized
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:685)
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:627)
        at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:541)
        at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:127)
        at org.eclipse.jgit.transport.Transport.push(Transport.java:1384)
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:137)
        ... 133 more
```

FYI., I have settings below on ~/.gradle/gradle.properties
```
signingSecretKeyRingFile=
signingKeyId=
signingPass=
sonatypeUser=
sonatypePass=
gitUsername=
gitPassword=
```

> And I have 2FA enabled. 

Please also let me know if any information is needed from my side. Thanks!

**Comment by ajoberstar** [comment]
See the documentation on [grgit authentication](https://ajoberstar.org/grgit/main/grgit-authentication.html) for how to configure this.
