### ISSUE TITLE
JgitUtil.resolveTag doesn't account for tags that point to other tags

### ISSUE THREAD

**Issue by vbuell** [ajoberstar/grgit#59]
```
error	05-May-2015 15:23:28	Caused by: groovy.lang.MissingMethodException: No signature of method: static org.ajoberstar.grgit.util.JGitUtil.convertCommit() is applicable for argument types: (org.eclipse.jgit.revwalk.RevTag) values: [tag 1eca2359f0969e94e04c281666590400aa315508 -----p]
error	05-May-2015 15:23:28	Possible solutions: convertCommit(org.eclipse.jgit.revwalk.RevCommit)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.util.JGitUtil$convertCommit$0.callStatic(Unknown Source)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.util.JGitUtil.resolveTag(JGitUtil.groovy:163)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.util.JGitUtil$resolveTag.call(Unknown Source)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.operation.TagListOp$_call_closure1.doCall(TagListOp.groovy:54)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.operation.TagListOp.call(TagListOp.groovy:53)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.operation.TagListOp.call(TagListOp.groovy)
error	05-May-2015 15:23:28		at java_util_concurrent_Callable$call$0.call(Unknown Source)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
error	05-May-2015 15:23:28		at org.ajoberstar.grgit.service.TagService.methodMissing(TagService.groovy:52)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.currentPosition(GitRepository.groovy:144)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$currentPosition$0.call(Unknown Source)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionResolver.resolveVersion(VersionResolver.groovy:19)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionResolver$resolveVersion.call(Unknown Source)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionService.currentDecoratedVersion(VersionService.groovy:34)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionService$currentDecoratedVersion.call(Unknown Source)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionConfig.getVersion(VersionConfig.groovy:82)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionConfig_Decorated.getVersion(Unknown Source)
error	05-May-2015 15:23:28		at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:153)
error	05-May-2015 15:23:28		at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:107)
error	05-May-2015 15:23:28		at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:78)
error	05-May-2015 15:23:28		at pl.allegro.tech.build.axion.release.domain.VersionConfig_Decorated.getProperty(Unknown Source)
```

**Comment by ajoberstar** [comment]
Do you have any more context about this error? There is a [test](https://github.com/ajoberstar/grgit/blob/master/src/test/groovy/org/ajoberstar/grgit/operation/TagListOpSpec.groovy) that covers the basic usage of `grgit.tag.list()`, so I'm guessing there's something different about your repository that I'm  not catching in the tests. Does your repo have annotated tags, lightweight, or both?

**Comment by vbuell** [comment]
The problem that we recreated tags from scratch so, unfortunately, I have no any evidence. Anyway, the issue is that the tag object pointed to another tag object. I believe, it was an annotated tag, as "In the case of an annotated tag the tag points to the tag object." (http://stefan.saasen.me/articles/git-clone-in-haskell-from-the-bottom-up/, also http://alblue.bandlem.com/2011/04/git-tip-of-week-tags.html)

**Comment by ajoberstar** [comment]
Ah, that makes sense. JGitUtil should keep traversing down the RevTag until it gets to a commit.

If you have time to put together a pull request that would be great. Otherwise, I'll plan to get it in the next release, though I don't know exactly when that would be.
